apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: graphql-demo
spec:
  selector:
    matchLabels:
      app: graphql-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: graphql-demo
    spec:
      containers:
        - name: graphql-demo
          image: gcr.io/GOOGLE_PROJECT_ID/IMAGE_NAME:IMAGE_VERSION
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=CLOUD_SQL_INSTANCE_CONNECTION_NAME=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
